import type { TileLanguage } from "../names.ts";

/**
 * THE WORDS THE ELEMENTS SAY, to a screen reader and in their own captions, in the two languages the family speaks.
 * An element speaks its own `lang`, or the nearest one above it, or the page's. `{name}` marks where a value goes
 * (`fillIn`).
 */
export const STRINGS: Readonly<Record<TileLanguage, Record<string, string>>> = {
  en: {
    tileFaceDown: "tile, face down",
    tileMarked: "{tile}, marked",
    tileLifted: "{tile}, raised",
    tileBlank: "tile, blank",
    rackLabel: "{n} tiles: {tiles}",
    rackEmpty: "no tiles",
    rackFaceDown: "{n} tiles, face down",
    groupLabel: "{group}: {tiles}",
    setLabel: "The set: {n} tiles in {faces} faces",
    setHolds: "{have} of {total} tiles",
    copies: "×{n}",
    viewerLabel: "Tile viewer",
    viewerNone: "No tile is called that.",
    viewerType: "Type a code, a name or a hand",
    viewerCode: "Code",
    viewerSuit: "Suit",
    viewerRank: "Rank",
    viewerCopies: "Copies in the set",
    viewerPoints: "Points at the table",
    viewerNotation: "Hand notation",
    viewerJapanese: "In Japanese",
    layoutLabel: "Mahjong layout, {n} tiles left",
    layoutLined: "{n} tiles lined up, sorted by {keys}",
    left: "{tiles} tiles left · {pairs} {pairsWord} you can take",
    pair: "pair",
    pairs: "pairs",
    stuck: "No pair can be taken. Shuffle the tiles that are left, or undo.",
    lost: "No shuffle can free what is left.",
    blocked: "That tile is not free: something lies on it, or both its sides are closed.",
    noMatch: "Those two do not match.",
    cleared: "Cleared, in {seconds} seconds.",
    timeUp: "Time is up.",
    newDeal: "New deal",
    undo: "Undo",
    hint: "Hint",
    shuffle: "Shuffle",
    hintsLeft: "{n} hints left",
    shufflesLeft: "{n} shuffles left",
    noHints: "No hints are left.",
    noShuffles: "No shuffles are left.",
    sortedBy: "Sorted by {keys}",
    gold: "Take the gold tile.",
    purge: "Take every {suit} tile.",
    tableTurn: "{name}, take a pair.",
    tableThinking: "{name} is thinking.",
    tableOver: "Done. Most points: {names}.",
    tableLabel: "Awase at a table of {n}",
    rush: "{done} of {goal} pairs",
    fortune: "{score} of {goal} points",
  },
  ja: {
    tileFaceDown: "伏せた牌",
    tileMarked: "{tile}、印あり",
    tileLifted: "{tile}、持ち上げ",
    tileBlank: "空白の牌",
    rackLabel: "{n}枚の牌：{tiles}",
    rackEmpty: "牌なし",
    rackFaceDown: "{n}枚の伏せた牌",
    groupLabel: "{group}：{tiles}",
    setLabel: "牌のセット：{faces}種類、{n}枚",
    setHolds: "{total}枚のうち{have}枚",
    copies: "×{n}",
    viewerLabel: "牌ビューア",
    viewerNone: "その名前の牌はありません。",
    viewerType: "コード、名前、手牌を入力",
    viewerCode: "コード",
    viewerSuit: "種類",
    viewerRank: "数",
    viewerCopies: "セットの枚数",
    viewerPoints: "卓での点",
    viewerNotation: "手牌表記",
    viewerJapanese: "日本語",
    layoutLabel: "麻雀の配置、残り{n}枚",
    layoutLined: "{n}枚を{keys}の順に並べました",
    left: "残り{tiles}枚・取れる組{pairs}",
    pair: "組",
    pairs: "組",
    stuck: "取れる組がありません。残りの牌を混ぜるか、戻してください。",
    lost: "混ぜても取れる牌が出ません。",
    blocked: "その牌はまだ取れません。上に牌が載っているか、両側がふさがっています。",
    noMatch: "その二枚は同じ牌ではありません。",
    cleared: "完成！{seconds}秒でした。",
    timeUp: "時間切れです。",
    newDeal: "新しく配る",
    undo: "戻す",
    hint: "ヒント",
    shuffle: "混ぜる",
    hintsLeft: "ヒントあと{n}回",
    shufflesLeft: "混ぜるあと{n}回",
    noHints: "ヒントはもうありません。",
    noShuffles: "混ぜる回数がもうありません。",
    sortedBy: "{keys}の順",
    gold: "金の牌を取ってください。",
    purge: "{suit}の牌をすべて取ってください。",
    tableTurn: "{name}さんの番です。一組取ってください。",
    tableThinking: "{name}が考えています。",
    tableOver: "終了。最高得点：{names}。",
    tableLabel: "{n}人の合わせ",
    rush: "{done}／{goal}組",
    fortune: "{score}／{goal}点",
  },
};

/** A string with its `{name}` places filled from the values given; a name with no value is left as it is. */
export function fillIn(text: string, values: Record<string, string | number>): string {
  return text.replace(/\{(\w+)\}/g, (whole, name: string) => (name in values ? String(values[name]) : whole));
}
