// The page's own words, in the two languages it speaks. Set as text, never as HTML.
export const WORDS = {
  en: {
    pageApi: "API reference",
    pitch: "Mahjong tiles for JavaScript and TypeScript, and the elements to put them on any page: a tile, a rack, a layout to play, a table, and viewers of the whole set. Below is Awase, the matching solitaire.",
    name: "Jarajara (ジャラジャラ) is the rattle of mahjong tiles being shuffled.",
    nameLink: "About the name",
    playTitle: "Awase, the matching solitaire",
    layout: "Layout",
    level: "Level",
    layouts: { tiny: "Tiny", torii: "Torii", fuji: "Fuji", castle: "Castle", turtle: "Turtle", pagoda: "Pagoda", fortress: "Fortress", pyramid: "Pyramid", bridge: "Bridge", butterfly: "Butterfly", dragon: "Dragon" },
    levels: { easy: "Easy", medium: "Medium", hard: "Hard" },
    showFree: "Light the free tiles",
    showMatching: "Ring the matches",
    findWord: "Find",
    aids: "Aids",
    viewWord: "View",
    views: { none: "Normal", horizontal: "Left-right", vertical: "Top-bottom", both: "Both" },
    tabTiles: "Tiles",
    tabRack: "Rack",
    tabSet: "Viewers",
    tabLayouts: "Layouts",
    tabTable: "Table",
    tabDesigns: "Designs",
    tabRules: "Rules",
    hints: "Hints",
    shuffles: "Shuffles",
    undoWord: "Undo",
    unlimited: "Unlimited",
    off: "None",
    on: "Allowed",
    howTo: "A tile is free when nothing lies on it and its left or right side is open. Tap a free tile, then its match.",
    tileTitle: "One tile",
    tileNote: "<jarajara-tile> is one tile on any page, in any design and with any back, tipped over on its edge by a tap. Name it by its letter or by any name it goes by.",
    pickTile: "Tile",
    designWord: "Design",
    backWord: "Back",
    sizeWord: "Size",
    sizeSmall: "Small",
    sizeMedium: "Medium",
    sizeLarge: "Large",
    soundWord: "Sound",
    challengeWord: "Challenge",
    challengeNone: "Plain",
    challenges: { gold: "Gold", spark: "Spark", rush: "Rush", fortune: "Fortune", sand: "Sand", purge: "Purge", blackout: "Blackout" },
    challengeNotes: {
      gold: "Take a pair of the gold face, four tiles ringed in gold. Hints and undo are allowed.",
      spark: "Clear the layout before time runs out, 2.5 seconds a tile. A pair of the spark face adds 20 seconds and sends the spark on. No undo.",
      rush: "Make the goal number of pairs in three minutes. The layout need not be cleared.",
      fortune: "Reach the goal score before time runs out. Pairs within five seconds of each other build a multiplier up to three.",
      sand: "Start with 45 seconds. Every pair adds five, a quick one a second more, to a limit of a minute. Clear the layout in time.",
      purge: "Take every tile of the marked group, ringed in gold, before time runs out.",
      blackout: "Only the free tiles show their faces; the covered ones stay blank. Hints are allowed, undo is not.",
    },
    daily: "Today's game",
    dailyNote: "Everybody gets the same layout, level and challenge today.",
    challengesTitle: "Challenges and options",
    challengesNote: "The same deal, played for something else. The options and the challenges are rules over a deal, never a change to it: every deal can still be cleared. Hints, shuffles and undo can be given, limited or taken away on any game.",
    redFive: "Red five",
    redFives: "Red fives",
    designOwn: "The design's own",
    designsTitle: "Designs",
    designsNote: "Jarajara's own tiles, and FluffyStuff's riichi tiles (public domain), regular and black, with their own backs and red fives. They are fetched the first time one is asked for. The riichi set has no flowers or seasons, so those stay Jarajara's own.",
    soundsTitle: "Sounds",
    soundsNote: "Tile clacks from real recordings, off until a page asks: nothing is fetched until the first one plays. Press a button to hear it, or the Sound switch to hear the game, the tile and the rack as you use them.",
    soundKinds: { pick: "Pick up", place: "Set down", flip: "Turn over", pair: "A pair", shuffle: "Shuffle", win: "A win" },
    rackTitle: "A rack of tiles",
    rackNote: "<jarajara-rack> lines tiles up in front of you. Tap a tile to raise it, then turn, sort, group, mix, take out, put in, mark and spin them.",
    rowTurn: "Turn over",
    rowOrder: "Order",
    rowChange: "Change",
    rowMark: "Mark",
    hide: "Face down",
    show: "Face up",
    hideSlow: "Face down, one by one",
    turnRaised: "Turn the raised",
    sortWord: "Sort",
    groupSuit: "Group by suit",
    groupKind: "Group by kind",
    ungroup: "Close the groups",
    unsort: "As dealt",
    mix: "Mix up",
    takeRaised: "Take the raised out",
    addTile: "Put a tile in",
    newHand: "New hand",
    markRaised: "Mark the raised",
    unmark: "Clear the marks",
    spin: "Spin",
    rackNone: "Nothing is raised: tap a tile first.",
    viewerTitle: "A tile looked up, and its group",
    viewerNote: "<jarajara-viewer> finds a tile by its code, its name in English or Japanese, or the notation hands are written in. <jarajara-group> shows a whole group of the set: a suit, the winds, the dragons, the flowers, the seasons.",
    groupWord: "Group",
    hiddenWord: "Face down, tap to learn",
    setTitle: "The whole set, as an inventory",
    setNote: "<jarajara-set> shows all 42 faces and how many of each the 144 tiles hold; give it a hand and it counts what the hand holds of the set.",
    modeFaces: "The 42 faces",
    modeTiles: "All 144 tiles",
    setHand: "A hand",
    setHandHint: "123m456p789s11z",
    setCount: (have, total) => `${have} of ${total} tiles`,
    backsTitle: "The backs",
    backsNote: "The tile backs, drawn: five of its own, recoloured or marked with a site's name, and the riichi sets bring theirs.",
    backColour: "Colour",
    backOwnColour: "Use this colour",
    backMark: "Mark",
    layoutsTitle: "A layout looked over",
    layoutsNote: "Any layout lined up and sorted by where its slots lie: across (x), down (y) and how high (z). Each tile says where it is.",
    sortLayer: "By layer",
    sortAcross: "Across",
    sortDown: "Down",
    sortTop: "Top first",
    inspectNote: (n, keys) => `${n} slots, sorted by ${keys}`,
    galleryTitle: "Every layout",
    galleryNote: "Each of the layouts, as a deal of it. Tap one to play it above.",
    tiles: "tiles",
    layers: "layers",
    tableTitle: "Awase at a table",
    tableNote: "<jarajara-table> seats two to four round one layout: every pair scores, a flower or season pair goes again, and the computers play the other seats.",
    playersWord: "Players",
    newDeal: "New deal",
    moreTitle: "Using it",
    moreText: "The page above is the package itself: the deal, the rules, the shuffle, the drawing and the elements. Each line below is all it takes.",
    foot: "Every deal is laid in reverse, so every deal can be cleared. Your game stays on this device.",
  },
  ja: {
    pageApi: "API（英語）",
    pitch: "JavaScriptとTypeScriptのための麻雀牌と、それをどのページにも置けるエレメントです。牌一枚、牌立て、遊べる配置、卓、そして牌の一覧。下は「合わせ」、牌を二枚ずつ取り除く一人遊びです。",
    name: "「ジャラジャラ」は、麻雀牌を混ぜるときの音です。",
    nameLink: "名前について（英語）",
    playTitle: "合わせ（一人遊び）",
    layout: "配置",
    level: "難しさ",
    layouts: { tiny: "小", torii: "鳥居", fuji: "富士", castle: "城", turtle: "亀", pagoda: "塔", fortress: "砦", pyramid: "角錐", bridge: "橋", butterfly: "蝶", dragon: "龍" },
    levels: { easy: "やさしい", medium: "ふつう", hard: "むずかしい" },
    showFree: "取れる牌を明るく",
    showMatching: "同じ牌を囲む",
    findWord: "探す",
    aids: "補助",
    viewWord: "視点",
    views: { none: "ふつう", horizontal: "左右", vertical: "上下", both: "両方" },
    tabTiles: "牌",
    tabRack: "牌立て",
    tabSet: "一覧",
    tabLayouts: "配置",
    tabTable: "卓",
    tabDesigns: "絵柄",
    tabRules: "ルール",
    hints: "ヒント",
    shuffles: "混ぜる回数",
    undoWord: "戻す",
    unlimited: "無制限",
    off: "なし",
    on: "あり",
    howTo: "上に何も載っておらず、左か右が空いている牌が取れます。取れる牌を押し、次に同じ牌を押します。",
    tileTitle: "牌一枚",
    tileNote: "<jarajara-tile> は、どのページにも置ける牌一枚です。どの絵柄、どの裏でも、押すとひっくり返ります。文字でも名前でも指定できます。",
    pickTile: "牌",
    designWord: "絵柄",
    backWord: "裏",
    sizeWord: "大きさ",
    sizeSmall: "小",
    sizeMedium: "中",
    sizeLarge: "大",
    soundWord: "音",
    challengeWord: "チャレンジ",
    challengeNone: "ふつう",
    challenges: { gold: "金", spark: "火花", rush: "速攻", fortune: "財運", sand: "砂時計", purge: "一掃", blackout: "暗転" },
    challengeNotes: {
      gold: "金の絵柄（金で囲んだ四枚）の組を取ります。ヒントと戻すは使えます。",
      spark: "時間内にすべて取ります（一枚2.5秒）。火花の絵柄の組を取ると20秒増え、火花が移ります。戻すは使えません。",
      rush: "三分で目標の組数を取ります。すべて取らなくても構いません。",
      fortune: "時間内に目標の点に届かせます。五秒以内に続けて取ると倍率が最大三倍まで上がります。",
      sand: "45秒から始めます。一組ごとに5秒、速ければさらに1秒増え、上限は1分。時間内にすべて取ります。",
      purge: "金で囲んだグループの牌を、時間内にすべて取ります。",
      blackout: "空いている牌だけ絵柄が見えます。覆われた牌は空白のままです。ヒントは使えますが、戻すは使えません。",
    },
    daily: "今日の一局",
    dailyNote: "今日は誰でも同じ配置、難しさ、チャレンジです。",
    challengesTitle: "チャレンジとオプション",
    challengesNote: "同じ配りを別の目的で遊びます。オプションもチャレンジも配りに重ねるルールで、配りは変わりません。どの配りも必ず完成できます。ヒント、混ぜる回数、戻すは、どの遊びでも与えたり、制限したり、なくしたりできます。",
    redFive: "赤五",
    redFives: "赤ドラ",
    designOwn: "絵柄の標準",
    designsTitle: "絵柄",
    designsNote: "Jarajaraの標準の牌と、FluffyStuffのリーチ麻雀牌（パブリックドメイン）の通常と黒。それぞれの裏と赤五つき。初めて使うときに読み込みます。リーチ牌には花牌と季節牌がないため、それらはJarajaraの絵のままです。",
    soundsTitle: "音",
    soundsNote: "本物の録音から作った牌の音です。頼まれるまで鳴らず、最初の一つが鳴るまで何も読み込みません。ボタンで音を聞くか、「音」スイッチで遊びながら聞けます。",
    soundKinds: { pick: "持ち上げる", place: "置く", flip: "裏返す", pair: "一組", shuffle: "混ぜる", win: "勝ち" },
    rackTitle: "牌立て",
    rackNote: "<jarajara-rack> は牌を目の前に並べます。牌を押すと持ち上がり、裏返す、整列、グループ分け、混ぜる、取り出す、加える、印をつける、回すができます。",
    rowTurn: "裏返す",
    rowOrder: "並べ方",
    rowChange: "入れ替え",
    rowMark: "印",
    hide: "伏せる",
    show: "表にする",
    hideSlow: "一枚ずつ伏せる",
    turnRaised: "上げた牌を裏返す",
    sortWord: "整列",
    groupSuit: "種類でまとめる",
    groupKind: "分類でまとめる",
    ungroup: "まとまりを閉じる",
    unsort: "配った順",
    mix: "混ぜる",
    takeRaised: "上げた牌を取り出す",
    addTile: "牌を加える",
    newHand: "新しい手牌",
    markRaised: "上げた牌に印",
    unmark: "印を消す",
    spin: "回す",
    rackNone: "上げた牌がありません。先に牌を押してください。",
    viewerTitle: "牌を調べる、グループを見る",
    viewerNote: "<jarajara-viewer> は、コード、英語や日本語の名前、手牌の表記から牌を探します。<jarajara-group> は、萬子・筒子・索子、風牌、三元牌、花牌、季節牌などのグループを見せます。",
    groupWord: "グループ",
    hiddenWord: "伏せて、押して覚える",
    setTitle: "セット全体（在庫）",
    setNote: "<jarajara-set> は42種類の牌と、144枚にそれぞれ何枚あるかを見せます。手牌を渡すと、セットのうち手牌が持つ枚数を数えます。",
    modeFaces: "42種類",
    modeTiles: "144枚すべて",
    setHand: "手牌",
    setHandHint: "123m456p789s11z",
    setCount: (have, total) => `${total}枚のうち${have}枚`,
    backsTitle: "牌の裏",
    backsNote: "牌の裏の絵です。独自の五種類は、色を変えたり、サイトの名前を入れたりできます。麻雀（リーチ）の絵柄はそれぞれの裏を持ってきます。",
    backColour: "色",
    backOwnColour: "この色を使う",
    backMark: "文字",
    layoutsTitle: "配置を見渡す",
    layoutsNote: "どの配置も、場所ごとに整列して並べられます。横（x）、縦（y）、高さ（z）。各牌に位置が書いてあります。",
    sortLayer: "段ごと",
    sortAcross: "横へ",
    sortDown: "縦へ",
    sortTop: "上から",
    inspectNote: (n, keys) => `${n}か所を ${keys} の順に整列`,
    galleryTitle: "すべての配置",
    galleryNote: "各配置を一つ配ったところです。押すと上で遊べます。",
    tiles: "枚",
    layers: "段",
    tableTitle: "卓で合わせ",
    tableNote: "<jarajara-table> は、二人から四人が一つの配置を囲みます。取った組は得点になり、花牌や季節牌の組はもう一度取れ、残りの席はコンピュータが打ちます。",
    playersWord: "人数",
    newDeal: "新しく配る",
    moreTitle: "使い方",
    moreText: "上のページは、このパッケージそのもの（配り方、ルール、混ぜ方、描き方、エレメント）で動いています。下の各行がそれぞれ必要なコードのすべてです。",
    foot: "どの配りも逆順に並べているので、必ず完成できます。遊びの続きはこの端末に残ります。",
  },
};
